home/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

profil/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
	url(r'^(?P<username>[\w.@+-]+)/$', views.index, name='profilhome'),
	url(r'^edit/(?P<username>[\w.@+-]+)/$', views.edit, name='editprofil'),
	url(r'^usernameedit/(?P<username>[\w.@+-]+)/$', views.usernameedit, name='usernameedit'),
	url(r'^emailedit/(?P<username>[\w.@+-]+)/$', views.emailedit, name='emailedit'),
	url(r'^namaedit/(?P<username>[\w.@+-]+)/$', views.namaedit, name='namaedit'),
]

webbantuin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^ngademin/', admin.site.urls),
	url(r'^', include('home.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^profil/', include('profil.urls', namespace='profil')),
    url(r'^kategori/', include('kategori.urls', namespace='kategori')),
    url(r'^jasa/', include('jasa.urls', namespace='jasa')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.handler404'
handler500 = 'home.views.handler500'

profil/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# memberi nama folder atau lokasi unggah avatar berdasarkan username yang menunggah
def upload_location(instance, filename):
	return "%s/%s" %(instance.user, filename)

# table database Profil untuk Profil App
class Profil(models.Model):
	# profil dasar
	user = models.ForeignKey(User, related_name='user')
	avatar = models.ImageField(upload_to=upload_location, blank=True)
	tgl_lahir = models.DateField()
	JENIS_KELAMIN = (
			('Pria', 'Pria'),
			('Wanita', 'Wanita'),
		)
	jenis_kelamin = models.CharField(max_length=12, choices=JENIS_KELAMIN)
	self_introduction = models.TextField()

	# alamat
	alamat = models.CharField(max_length=200)
	kode_pos = models.CharField(max_length=6)
	desa = models.CharField(max_length=150)
	kecamatan = models.CharField(max_length=150)
	kabupaten = models.CharField(max_length=150)
	provinsi = models.CharField(max_length=150)
	negara = models.CharField(max_length=150)

	# Kontak
	phone = models.CharField(max_length=150)
	website = models.URLField(blank=True)
	fb = models.URLField(blank=True)
	twitter = models.URLField(blank=True)
	googleplus = models.URLField(blank=True)

	# lain-lain
	STATUS_PEKERJA = (
			('Bukan Pekerja', 'Bukan Pekerja'),
			('Pekerja', 'Pekerja'),
		)
	statuspekerja = models.CharField(max_length=24, choices=STATUS_PEKERJA, default='Bukan Pekerja', blank=True)
	BAHASA = (
			('Bahasa Indonesia', 'Bahasa Indonesia'),
			('English', 'English'),
			('Other', 'Other'),
		)
	bahasa = models.CharField(max_length=150, choices=BAHASA)

profil/forms.py
from django.forms import ModelForm
from django import forms

from .models import Profil
from django.contrib.auth.models import User

# forms Nama depan dan Nama belakang
class FullnameForm(ModelForm):
	first_name = forms.CharField(
		required = True,
		label = 'Nama Depan',
		widget = forms.TextInput(
			attrs = {'placeholder': 'Nama Depan'}
			)
		)

	last_name = forms.CharField(
		required = True,
		label = 'Nama Belakang',
		widget = forms.TextInput(
			attrs = {'placeholder': 'Nama Belakang'}
			)
		)

	class Meta:
		model = User
		fields = [
			"first_name",
			"last_name",
		]

# forms Username
class UsernameForm(ModelForm):
	username = forms.CharField(
		required = True,
		label = 'Username',
		max_length = 50,
		widget = forms.TextInput(
			attrs = {'placeholder': 'Your Username'}
			)
		)

	class Meta:
		model = User
		fields = [
			"username",
		]

# forms Email
class EmailForm(ModelForm):
	email = forms.EmailField(
		required = True,
		label = 'Email',
		widget = forms.TextInput(
			attrs = {'placeholder': 'Email'}
			)
		)

	class Meta:
		model = User
		fields = [
			"email",
		]

# tipe tanggal untuk tgl_lahir
class DateInput(forms.DateInput):
	input_type = 'date'

# forms Profil
class ProfilForm(ModelForm):
	class Meta:
		model = Profil

		fields = [
			# profil dasar
			"user",
			"avatar",
			"tgl_lahir",
			"jenis_kelamin",
			"self_introduction",

			# alamat
			"alamat",
			"kode_pos",
			"desa",
			"kecamatan",
			"kabupaten",
			"provinsi",
			"negara",

			# kontak
			"phone",
			"website",
			"fb",
			"twitter",
			"googleplus",

			# lain-lain
			"statuspekerja",
			"bahasa",
		]

		labels = {
			# profil dasar
			'avatar': "Avatar",
			'tgl_lahir': "Tanggal Lahir",
			'jenis_kelamin': "Jenis Kelamin",
			'self_introduction': "Tentang Saya",

			# alamat
			'alamat': "Alamat",
			'kode_pos': "Kode Pos",
			'desa': "Desa",
			'kecamatan': "Kecamatan",
			'kabupaten': "Kabupaten/Kota",
			'provinsi': "Provinsi",
			'negara': "Negara",

			# kontak
			'phone': "Phone",
			'website': "Website",
			'fb': "Facebook",
			'twitter': "Twitter",
			'googleplus': "Google Plus",

			# lain-lain
			'statuspekerja': "Status Pekerja",
			'bahasa': "Bahasa",
		}

		widgets = {
			# profil dasar
			'self_introduction': forms.Textarea(attrs= {'placeholder': 'Deskripsikan tentang diri anda'}),
			'tgl_lahir': DateInput(),

			# alamat
			'alamat': forms.TextInput(attrs= {'placeholder': 'Alamat Lengkap'}),
			'kode_pos': forms.TextInput(attrs= {'placeholder': 'Kode Pos', 'type': 'number', 'min': '0'}),
			'desa': forms.TextInput(attrs= {'placeholder': 'Desa'}),
			'kecamatan': forms.TextInput(attrs= {'placeholder': 'Kecamatan'}),
			'kabupaten': forms.TextInput(attrs= {'placeholder': 'Kabupaten/Kota'}),
			'provinsi': forms.TextInput(attrs= {'placeholder': 'Provinsi'}),
			'negara': forms.TextInput(attrs= {'placeholder': 'Negara'}),

			#kontak
			'phone': forms.TextInput(attrs= {'placeholder': 'Nomor Telepon', 'type': 'number', 'min': '0'}),
			'website': forms.TextInput(attrs= {'placeholder': 'http://websiteanda.domain'}),
			'fb': forms.TextInput(attrs= {'placeholder': 'http://facebook.com/namaprofil'}),
			'twitter': forms.TextInput(attrs= {'placeholder': 'http://twitter.com/namaprofil'}),
			'googleplus': forms.TextInput(attrs= {'placeholder': 'http://plus.google.com/+namaprofil'}),
		}

profil/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.conf import settings

from django.contrib.auth.models import User
from kategori.models import Kategori
from .models import Profil
from .forms import ProfilForm, EmailForm, FullnameForm, UsernameForm

# index view profil
def index(request, username):
	
	getusrname = get_object_or_404(User, username=username) # mendapatkan username, namun jika tidak menemukan akan diarahkan ke halaman 404

	getkategori = Kategori.objects.all().order_by("kategori")

	getprofil = Profil.objects.filter(user__username=username).first() # mendapatkan data dari tabel profil dengan pemicu username yang sudah didapatkan

	getavatarusr = Profil.objects.filter(user__username=request.user.username).first() # # mendapatkan data link foto / avatar
	
	context = {
		"getusrname": getusrname,
		"kategori_list": getkategori,
		"getprofil": getprofil,
		"getavatarusr": getavatarusr,
	}

	return render(request, 'profil/profil.html', context)

# view edit profil
@login_required(login_url=settings.LOGIN_URL)
def edit(request, username):
	
	getusrname = get_object_or_404(User, username=username)

	getkategori = Kategori.objects.all().order_by("kategori")

	getprofil = Profil.objects.filter(user__username=username).first()

	getavatarusr = Profil.objects.filter(user__username=request.user.username).first()

	if request.method == 'POST':
		form = ProfilForm(request.POST or None, request.FILES or None, instance=getprofil)
		if form.is_valid():
			profil = form.save(commit = False)
			profil.save()
			messages.success(request, 'Perubahan pada profil anda telah tersimpan.', extra_tags='alert alert-success')
			return HttpResponseRedirect('../../../profil/'+getusrname.username) # << redirect pakai url macam apa ini -_-
		else:
			messages.warning(request, 'Anda gagal melakukan perubahan pada profil.', extra_tags='alert alert-danger')
			return HttpResponseRedirect('../../../profil/'+getusrname.username) # << redirect pakai url macam apa ini -_-
	else:
		form = ProfilForm(instance=getprofil)

	context = {
		"getusrname": getusrname,
		"kategori_list": getkategori,
		"getprofil": getprofil,
		"getavatarusr": getavatarusr,	
		"form": form,
	}

	return render(request, 'profil/edit_profil.html', context)

# view edit username
@login_required(login_url=settings.LOGIN_URL)
def usernameedit(request, username):
	
	getusrname = get_object_or_404(User, username=username)

	getkategori = Kategori.objects.all().order_by("kategori")

	getavatarusr = Profil.objects.filter(user__username=request.user.username).first()

	if request.method == 'POST':
		form = UsernameForm(request.POST or None, instance=getusrname)
		if form.is_valid():
			username = form.save(commit = False)
			username.save()
			messages.success(request, 'Perubahan pada username anda telah tersimpan.', extra_tags='alert alert-success')
			return HttpResponseRedirect('../../../profil/'+getusrname.username) # << redirect pakai url macam apa ini -_-
		else:
			messages.warning(request, 'Anda gagal melakukan perubahan pada profil.', extra_tags='alert alert-danger')
			return HttpResponseRedirect('../../../profil/'+getusrname.username) # << redirect pakai url macam apa ini -_-
	else:
		form = UsernameForm(instance=getusrname)

	context = {
		"getusrname": getusrname,
		"kategori_list": getkategori,
		"getavatarusr": getavatarusr,
		"form": form,
	}

	return render(request, 'profil/username_edit.html', context)

# view edit email
@login_required(login_url=settings.LOGIN_URL)
def emailedit(request, username):
	
	getusrname = get_object_or_404(User, username=username)

	getkategori = Kategori.objects.all().order_by("kategori")

	getavatarusr = Profil.objects.filter(user__username=request.user.username).first()

	if request.method == 'POST':
		form = EmailForm(request.POST or None, instance=getusrname)
		if form.is_valid():
			email = form.save(commit = False)
			email.save()
			messages.success(request, 'Perubahan pada email anda telah tersimpan.', extra_tags='alert alert-success')
			return HttpResponseRedirect('../../../profil/'+getusrname.username) # << redirect pakai url macam apa ini -_-
		else:
			messages.warning(request, 'Anda gagal melakukan perubahan pada profil.', extra_tags='alert alert-danger')
			return HttpResponseRedirect('../../../profil/'+getusrname.username) # << redirect pakai url macam apa ini -_-
	else:
		form = EmailForm(instance=getusrname)

	context = {
		"getusrname": getusrname,
		"kategori_list": getkategori,
		"getavatarusr": getavatarusr,
		"form": form,
	}

	return render(request, 'profil/email_edit.html', context)

# view edit nama depan dan belakang
@login_required(login_url=settings.LOGIN_URL)
def namaedit(request, username):
	
	getusrname = get_object_or_404(User, username=username)

	getkategori = Kategori.objects.all().order_by("kategori")

	getavatarusr = Profil.objects.filter(user__username=request.user.username).first()

	if request.method == 'POST':
		form = FullnameForm(request.POST or None, instance=getusrname)
		if form.is_valid():
			fullname = form.save(commit = False)
			fullname.save()
			messages.success(request, 'Perubahan pada nama anda telah tersimpan.', extra_tags='alert alert-success')
			return HttpResponseRedirect('../../../profil/'+getusrname.username) # << redirect pakai url macam apa ini -_-
		else:
			messages.warning(request, 'Anda gagal melakukan perubahan pada profil.', extra_tags='alert alert-danger')
			return HttpResponseRedirect('../../../profil/'+getusrname.username) # << redirect pakai url macam apa ini -_-
	else:
		form = FullnameForm(instance=getusrname)

	context = {
		"getusrname": getusrname,
		"kategori_list": getkategori,
		"getavatarusr": getavatarusr,
		"form": form,
	}

	return render(request, 'profil/fullname_edit.html', context)

profil/templates/profil/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <!--loadtitle-->
    <title>{% block title %}{% endblock %}</title>

    <!--load main css and more-->
    {% include "profil/head.html" %}


</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
            {% include "profil/nav.html" %}
        </nav>
        {% include "profil/sidebar.html" %}

    <!--load content-->
    {% block content %}{% endblock%}

    </div>
    <!-- /#wrapper -->

    <!--load main js-->
    {% include "profil/js.html" %}

</body>

</html>

profil/templates/profil/edit_profil.html
<!--load base profillayout-->
{% extends 'profil/base.html' %}

<!-- load crispy forms tags -->
{% load crispy_forms_tags %}

<!-- load widget tweaks -->
{% load widget_tweaks %}

<!--judul-->
{% block title %} {{ getusrname.username }} Edit Profil | Bantuin {% endblock %}

<!--konten-->
{% block content %}

<div id="page-wrapper" style="margin-top:35px">
    <div class="row">
        <div class="col-lg-12">

            {% if user.username == getusrname.username %}

			<h1 class="page-header">Edit Profil {{ getusrname.username }}</h1>
			
			<div class="alert alert-danger" role="alert">
				<p>
		            <strong>upload avatar tidak dapat digunakan pada situs contoh ini.</strong><br>
		        	<strong>upload avatar hanya dapat digunakan pada localhost atau development mode</strong>
		    	</p>
		    </div>

			<div class="col-lg-4">
                <p>
	            {% if getprofil.avatar.url != None %}
				<img src="{{ getprofil.avatar.url }}" class="img-responsive img-thumbnail img-rounded center-block">
				{% else %}
				<img src="/static/img/users.svg" class="img-responsive img-thumbnail img-rounded center-block">
				{% endif %}
				</p>
            </div>
            <div class="col-lg-7">
            <p>
            	<strong>Display Name : </strong> {{ getusrname.first_name }} {{ getusrname.last_name }} <a href="/profil/namaedit/{{ getusrname.username }}"><i class="fa fa-pencil fa-fw"></i></a>
            </p>
            <p>
            	<strong>User Name : </strong> {{ getusrname.username }} <a href="/profil/usernameedit/{{ getusrname.username }}"><i class="fa fa-pencil fa-fw"></i></a>
            </p>
            <p>
            	<strong>Email : </strong> <a href="mailto:{{ getusrname.email }}">{{ getusrname.email }}</a> <a href="/profil/emailedit/{{ getusrname.username }}"><i class="fa fa-pencil fa-fw"></i></a>
            </p>
			<form action="." method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<!-- profil dasar -->
				<select name="user" id="id_user" style="visibility:hidden;">
					<option value="{{ getusrname.id }}" selected="{{ getusrname.id }}">{{ getusrname.id}}</option>
				</select>
				{{ form.avatar|as_crispy_field }}
				{{ form.tgl_lahir|as_crispy_field }}
				{{ form.jenis_kelamin|as_crispy_field }}
				{{ form.self_introduction|as_crispy_field }}
				<!-- alamat -->
				{{ form.alamat|as_crispy_field }}
				{{ form.kode_pos|as_crispy_field }}
				{{ form.desa|as_crispy_field }}
				{{ form.kecamatan|as_crispy_field }}
				{{ form.kabupaten|as_crispy_field }}
				{{ form.provinsi|as_crispy_field }}
				{{ form.negara|as_crispy_field }}
				<!-- kontak -->
				{{ form.phone|as_crispy_field }}
				{{ form.website|as_crispy_field }}
				{{ form.fb|as_crispy_field }}
				{{ form.twitter|as_crispy_field }}
				{{ form.googleplus|as_crispy_field }}
				<!-- lain-lain -->
				{{ form.statuspekerja|as_crispy_field }}
				{{ form.bahasa|as_crispy_field }}
				<button type="submit" class="btn btn-primary btn-lg btn-block">Simpan</button><br><br><br>
			</form>
			</div>

		{% else %}

			<meta http-equiv="refresh" content="0; url=/">

		{% endif %}

        </div>
        <!-- /.col-lg-12 -->
    </div>            
</div>
<!-- /#page-wrapper -->

{% endblock %}

profil/templates/profil/email_edit.html
<!--load base profillayout-->
{% extends 'profil/base.html' %}

<!-- load crispy forms tags -->
{% load crispy_forms_tags %}

<!--judul-->
{% block title %} {{ getusrname.username }} Edit Email | Bantuin {% endblock %}

<!--konten-->
{% block content %}

<div id="page-wrapper" style="margin-top:35px">
    <div class="row">
        <div class="col-lg-12">
            {% if user.username == getusrname.username %}

			<h1 class="page-header">Ubah Email {{ getusrname.username }}</h1>

			<form action="." method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form|crispy }}
				<input type="submit" class="btn btn-primary" value="Simpan">
			</form>

		{% else %}

			<meta http-equiv="refresh" content="0; url=/">

		{% endif %}

        </div>
        <!-- /.col-lg-12 -->
    </div>            
</div>
<!-- /#page-wrapper -->

{% endblock %}

profil/templates/profil/fullname_edit.html
<!--load base profillayout-->
{% extends 'profil/base.html' %}

<!-- load crispy forms tags -->
{% load crispy_forms_tags %}

<!--judul-->
{% block title %} {{ getusrname.username }} Edit Nama | Bantuin {% endblock %}

<!--konten-->
{% block content %}

<div id="page-wrapper" style="margin-top:35px">
    <div class="row">
        <div class="col-lg-12">
            {% if user.username == getusrname.username %}

			<h1 class="page-header">Edit Nama Lengkap</h1>

			<form action="." method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form|crispy }}
				<input type="submit" class="btn btn-primary" value="Simpan">
			</form>

		{% else %}

			<meta http-equiv="refresh" content="0; url=/">

		{% endif %}

        </div>
        <!-- /.col-lg-12 -->
    </div>            
</div>
<!-- /#page-wrapper -->

{% endblock %}

profil/templates/profil/nav.html
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/" style="font-size: 28px"><strong>Bantuin</a>
</div>
<!-- /.navbar-header -->
<ul class="nav navbar-top-links navbar-right">
    <!-- /.dropdown -->
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            {% if user.is_authenticated %}
                {% if getavatarusr.avatar.url != None %}
                <img src="{{ getavatarusr.avatar.url }}" class="img-circle" alt="User Image" style="height: 20px;">
                {% else %}
                <img src="/static/img/users.svg" class="img-circle" alt="User Image" style="height: 20px;">
                {% endif %}
                {{ user.username }}
            {% else %}
                <strong>Profil</strong>
            {% endif %}
            <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            {% if user.is_authenticated %}
            <li>
                <a href="/profil/{{ user.username }}"><i class="fa fa-user fa-fw"></i> Profil Saya</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="{% url 'auth_logout' %}"><i class="fa fa-sign-out fa-fw"></i> Keluar</a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'auth_login' %}"><i class="fa fa-sign-out fa-fw"></i> Login</a>
            </li>
            {% endif %}
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
</ul>
<!-- /.navbar-top-links -->

profil/templates/profil/sidebar.html
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <a href="/"><i class="fa fa-home fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-book fa-fw" aria-hidden="true"></i> Kategori Bantuan <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="/kategori/">Semua Kategori Bantuan</a>
                    </li>
                    {% for kategori in kategori_list %}
                    <li>
                        <a href="/kategori/{{ kategori.k_slug }}/">{{ kategori | title }}</a>
                    </li>
                    {% endfor %}
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="/about/"><i class="fa fa-info-circle fa-fw"></i> Tentang Bantuin</a>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->

profil/templates/profil/username_edit.html
<!--load base profillayout-->
{% extends 'profil/base.html' %}

<!-- load crispy forms tags -->
{% load crispy_forms_tags %}

<!--judul-->
{% block title %} {{ getusrname.username }} Edit Username | Bantuin {% endblock %}

<!--konten-->
{% block content %}

<div id="page-wrapper" style="margin-top:35px">
    <div class="row">
        <div class="col-lg-12">
            {% if user.username == getusrname.username %}

			<h1 class="page-header">Edit Username {{ getusrname.username }}</h1>

			<form action="." method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form|crispy }}
				<input type="submit" class="btn btn-primary btn-lg btn-block" value="Simpan">
			</form>

		{% else %}

			<meta http-equiv="refresh" content="0; url=/">

		{% endif %}

        </div>
        <!-- /.col-lg-12 -->
    </div>            
</div>
<!-- /#page-wrapper -->

{% endblock %}